wiseconnect: Fix compiler warning
gcc 14.3 complains:

    error: conflicting types for
    'sl_si91x_gpio_select_group_interrupt_wakeup' due to enum/integer
    mismatch; have 'void(uint8_t, sl_si91x_group_interrupt_t, uint8_t)'
    {aka 'void(unsigned char, sl_si91x_group_interrupt_t, unsigned
    char)'} [-Werror=enum-int-mismatch]

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>