wiseconnect: Fix typo in EXTENTION
Zephyr CI raise errors for misspelled words. So, the Zephyr code uses
"EXTENSION" while HAL still use "EXTENTION".

Note, the upstream tried to fix the issue by adding a bunch of #ifdef
__ZEPHYR__. Unfortunately, it produce these kind of errors:

    .../sl_net.c: In function 'sl_net_init':
    .../sl_net.c:57:40: error: 'sl_wifi_default_client_configuration' undeclared (first use in this function); did you mean 'sl_wifi_advanced_client_configuration_t'?
       57 |         configuration = (const void *)&sl_wifi_default_client_configuration;
          |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                                        sl_wifi_advanced_client_configuration_t
    .../sl_net.c:57:40: note: each undeclared identifier is reported only once for each function it appears in
    .../sl_net.c:100:40: error: 'sl_wifi_default_ap_configuration' undeclared (first use in this function); did you mean 'sl_wifi_advanced_ap_configuration_t'?
      100 |         configuration = (const void *)&sl_wifi_default_ap_configuration;
          |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                                        sl_wifi_advanced_ap_configuration_t

... so this patch also undoes this change.

Upstream-status: Pending
Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>