scripts: gen_pinctrl: Fix Python comaptibility
On Debian with Python 3.1, I get this error:

  File ".../silabs/scripts/gen_pinctrl.py", line 325
    lines.append(f"#define ABUS_{abus["bus_name"]}_{abus["peripher ...
                                       ^^^^^^^^
  SyntaxError: f-string: unmatched '['

Obviously, my Python does not support nested double quotes ("). Probably
the feature has been introduced in newer Python versions.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>